# Generated by Django 2.2.7 on 2019-11-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.CharField(default='/images/cool.png', max_length=255)),
                ('neutral', models.CharField(default='/images/neutral.png', max_length=255)),
                ('angry', models.CharField(default='/images/angry.png', max_length=255)),
                ('disgust', models.CharField(default='/images/disgust.png', max_length=255)),
                ('fear', models.CharField(default='/images/fear.png', max_length=255)),
                ('sad', models.CharField(default='/images/crying.png', max_length=255)),
                ('surprise', models.CharField(default='/images/surprised.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
