# Generated by Django 2.2.7 on 2019-11-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='emoji_image',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='percent_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='target_emo',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='user_picture',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
